[workspace]
resolver = "2"

members = [
    # 1. The core Vexo framework library
    "vexo",

    # 2. The platform-agnostic application logic (for desktop and mobile exports)
    "shared_app",

    # 3. The executable that runs the shared_app logic on the desktop
    "desktop_demo",
]

# ------------------------------------------------------------------------
# [workspace.dependencies]
# ------------------------------------------------------------------------
# This section centralizes common dependency versions. Member crates can
# now reference these versions using a syntax like `wgpu = { workspace = true }`
# or `winit = { workspace = true }`.

[workspace.dependencies]
# Graphics & Windowing
wgpu = "27.0.1"
winit = "0.31.0-beta.2"

# Layout Engine
taffy = "0.9.1"

# Utility
pollster = "0.4.0"
bytemuck = "1.24.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"

# Text Rendering 
glyphon = { git = "https://github.com/grovesNL/glyphon.git", branch = "main" }

# Foreign Function Interface (for mobile exports)
uniffi = {version = "0.30.0", features = ["cli"] }
