//! `InheritedWidget` trait and `InheritedElement` — the provider primitive.
//!
//! An `InheritedWidget` exposes an immutable value of type `Self::Value` to
//! all descendants. Dependents read it via
//! `RenderContext::depend_on_inherited_widget::<V>()` (added in a later task)
//! and auto-rebuild when the value changes (the provider's `update()` calls
//! `BuildOwner::mark_needs_build` on each dependent).
//!
//! See `docs/superpowers/specs/2026-07-12-inherited-widget-design.md`.

use std::any::{Any, TypeId};

use crate::element::Element;
use crate::element_context::ElementContext;
use crate::elements::RenderObjectElement;
use crate::focus::attachment::FocusAttachment;
use crate::id::{ElementKey, RenderObjectKey};
use crate::inherited_registry::InheritedMap;
use crate::key::WidgetKey;
use crate::widgets::Widget;

/// A widget that exposes a value of type `Self::Value` to all descendants.
///
/// Immutable: to change the value, an ancestor rebuilds with a new
/// `InheritedWidget`. Dependents auto-rebuild via the `InheritedRegistry`.
///
/// Requires `Clone` so the `Widget` impl (generated by
/// [`impl_widget_for_inherited!`]) can satisfy `clone_boxed()`.
///
/// # Implementing
///
/// ```ignore
/// #[derive(Clone)]
/// struct MyEnv { value: u32, child: Box<dyn Widget> }
///
/// impl InheritedWidget for MyEnv {
///     type Value = u32;
///     fn value(&self) -> &u32 { &self.value }
///     fn child(&self) -> &dyn Widget { self.child.as_ref() }
/// }
///
/// impl_widget_for_inherited!(MyEnv);
/// ```
///
/// # Why a macro instead of a blanket impl?
///
/// The crate already has `impl<W: Component + Clone + 'static> Widget for W`.
/// A blanket `impl<T: InheritedWidget> Widget for T` would overlap with it
/// (a type could implement both `Component` and `InheritedWidget`), which
/// Rust's coherence rules reject. Without negative trait bounds (unstable),
/// the cleanest workaround is a macro that generates the `Widget` impl per
/// concrete `InheritedWidget` type.
pub trait InheritedWidget: Clone + 'static {
    /// The value type exposed to descendants. `Clone + PartialEq + Send + Sync`
    /// so the default `update_should_notify` can compare old vs new, and so
    /// the value can be stored in `InheritedRegistry`'s
    /// `Box<dyn Any + Send + Sync>` slot.
    type Value: Clone + PartialEq + Send + Sync + 'static;

    /// The current value exposed to descendants.
    fn value(&self) -> &Self::Value;

    /// The single child subtree that gets access to this value.
    fn child(&self) -> &dyn Widget;

    /// Optional key for identity across frames (default `None`).
    fn key(&self) -> Option<WidgetKey> {
        None
    }

    /// Whether updating `old → new` should rebuild dependents.
    ///
    /// Default: rebuild iff `value()` changed.
    fn update_should_notify(&self, old: &Self, new: &Self) -> bool {
        old.value() != new.value()
    }
}

/// Generates the `Widget` impl for a concrete `InheritedWidget` type.
///
/// Bridges `InheritedWidget` (provider trait) to `Widget` (the widget-tree
/// trait). Creates an `InheritedElement` and a pass-through `ProxyRenderObject`
/// (reused from `stateful_widget.rs`).
///
/// See [`InheritedWidget`] docs for why this is a macro rather than a blanket
/// impl.
macro_rules! impl_widget_for_inherited {
    ($t:ty) => {
        impl $crate::widgets::Widget for $t {
            fn key(&self) -> Option<$crate::key::WidgetKey> {
                <Self as $crate::inherited_widget::InheritedWidget>::key(self)
            }

            fn create_element(&self) -> Box<dyn $crate::element::Element> {
                Box::new($crate::inherited_widget::InheritedElement::<$t>::new(
                    self.clone(),
                ))
            }

            fn create_render_object(&self) -> Box<dyn $crate::render_object::RenderObject> {
                Box::new($crate::stateful_widget::ProxyRenderObject::new())
            }

            fn as_any(&self) -> &dyn::std::any::Any {
                self
            }

            fn child(&self) -> Option<&dyn $crate::widgets::Widget> {
                Some(<Self as $crate::inherited_widget::InheritedWidget>::child(
                    self,
                ))
            }

            fn update_render_object(
                &self,
                _render_object: &mut dyn $crate::render_object::RenderObject,
            ) -> $crate::update_result::UpdateResult {
                // InheritedWidget's only mutable state is the value, which
                // lives in the registry, not the render object. The proxy RO
                // has no layout/paint-affecting properties.
                $crate::update_result::UpdateResult::NONE
            }

            fn clone_boxed(&self) -> Box<dyn $crate::widgets::Widget> {
                Box::new(self.clone())
            }
        }
    };
}
pub(crate) use impl_widget_for_inherited;

/// Element backing an `InheritedWidget`. Registers itself as a provider in
/// `InheritedRegistry` at mount, marks dependents dirty on update, and
/// unregisters at unmount.
pub struct InheritedElement<W: InheritedWidget> {
    widget: W,
    id: Option<ElementKey>,
    key: Option<WidgetKey>,
    render_object_id: Option<RenderObjectKey>,
    /// The `Arc<InheritedMap>` this element produced for its subtree.
    /// Held so children can read it; dropped on unmount.
    subtree_map: Option<std::sync::Arc<InheritedMap>>,
    focus_attachment: Option<FocusAttachment>,
}

impl<W: InheritedWidget> InheritedElement<W> {
    pub fn new(widget: W) -> Self {
        Self {
            widget,
            id: None,
            key: None,
            render_object_id: None,
            subtree_map: None,
            focus_attachment: None,
        }
    }

    fn type_id_of_value() -> TypeId {
        TypeId::of::<W::Value>()
    }

    fn get_child_widget(&self) -> &dyn Widget {
        self.widget.child()
    }
}

impl<W: InheritedWidget + Widget> RenderObjectElement for InheritedElement<W> {
    fn widget(&self) -> Option<&dyn Widget> {
        Some(&self.widget)
    }

    fn set_widget(&mut self, widget: Box<dyn Widget>) {
        if let Some(w) = widget.as_any().downcast_ref::<W>() {
            self.widget = w.clone();
        }
    }

    fn render_object_id(&self) -> Option<RenderObjectKey> {
        self.render_object_id
    }

    fn set_render_object_id(&mut self, id: Option<RenderObjectKey>) {
        self.render_object_id = id;
    }

    fn stored_key(&self) -> Option<WidgetKey> {
        self.key.clone()
    }

    fn set_stored_key(&mut self, key: Option<WidgetKey>) {
        self.key = key;
    }

    fn element_id(&self) -> Option<ElementKey> {
        self.id
    }

    fn set_element_id(&mut self, id: Option<ElementKey>) {
        self.id = id;
    }
}

impl<W: InheritedWidget + Widget> Element for InheritedElement<W> {
    fn mount(&mut self, context: &mut ElementContext) {
        let element_key = context.element_id;

        // 1. Focus node (same pattern as SafeAreaElement).
        let parent_id = context.parent_focus_node_id();
        let node_id = context
            .focus_manager()
            .create_node_for_element(element_key, parent_id);
        if let Some(node_id) = node_id {
            self.focus_attachment = Some(FocusAttachment::new(node_id));
        }

        // 2. Register self as a provider in InheritedRegistry.
        let type_id = Self::type_id_of_value();
        context.inherited_registry.register_provider(
            element_key,
            type_id,
            Box::new(self.widget.value().clone()),
        );

        // 3. Build this element's subtree map: parent's map + self.
        // The pipeline stores this map so children can read it.
        let new_map = context.inherited_map.with_insert(type_id, element_key);
        let arc = std::sync::Arc::new(new_map);
        context
            .inherited_map_storage
            .insert(element_key, arc.clone());
        self.subtree_map = Some(arc);

        // 4. Mount render object (pass-through proxy).
        self.mount_render_object(context);

        // 5. Inflate child — child's mount will receive this element's map
        // (the reconciler passes `self.subtree_map` as the child's
        // `inherited_map` by looking it up in `inherited_map_storage`).
        context.inflate_child(None, self.get_child_widget().clone_boxed());
    }

    fn update(&mut self, new_widget: Box<dyn Any>, context: &mut ElementContext) {
        // Downcast to W.
        let new_w: W = {
            if let Ok(boxed) = new_widget.downcast::<Box<dyn Widget>>() {
                if let Some(w) = boxed.as_any().downcast_ref::<W>() {
                    w.clone()
                } else {
                    return;
                }
            } else {
                return;
            }
        };

        let should_notify = self.widget.update_should_notify(&self.widget, &new_w);
        self.widget = new_w;

        if should_notify {
            let element_key = context.element_id;
            let type_id = Self::type_id_of_value();
            // Update the stored value.
            context.inherited_registry.update_value(
                element_key,
                type_id,
                Box::new(self.widget.value().clone()),
            );
            // Mark all dependents dirty.
            let deps = context.inherited_registry.dependents_for(element_key);
            for dep in deps {
                context.build_owner.mark_needs_build(dep);
            }
        }

        // Reconcile child via child_ops (same as SafeAreaElement::rebuild).
        let old_child = context.children().first().copied();
        let child_widget = self.get_child_widget().clone_boxed();
        match old_child {
            Some(old_child_key) => {
                context.update_child(old_child_key, child_widget);
            }
            None => {
                context.inflate_child(None, child_widget);
            }
        }

        if let Some(attachment) = self.focus_attachment.as_ref() {
            let new_parent_id = context.parent_focus_node_id();
            attachment.reparent_to(new_parent_id, context.focus_manager());
        }
    }

    fn unmount(&mut self, context: &mut ElementContext) {
        let element_key = context.element_id;

        // Remove from registry first (drops value + dependents).
        context.inherited_registry.remove_provider(element_key);

        // Clear the pipeline's per-element map storage entry.
        context.inherited_map_storage.remove(element_key);

        // Drop subtree map.
        self.subtree_map = None;

        // Use RenderObjectElement's default unmount.
        self.unmount_render_object(context);

        // Unmount child.
        if let Some(child_key) = context.children().first().copied() {
            context.unmount_child(child_key);
        }

        // Detach focus node.
        if let Some(mut attachment) = self.focus_attachment.take() {
            attachment.detach(context.focus_manager());
        }
    }

    fn render_object(&self) -> Option<RenderObjectKey> {
        self.render_object_id
    }

    fn widget_key(&self) -> Option<WidgetKey> {
        self.key.clone()
    }

    fn can_update(&self, widget: &dyn Any) -> bool {
        widget.downcast_ref::<W>().is_some()
    }

    fn child_mounted(
        &mut self,
        _slot: Option<usize>,
        child_ro: Option<RenderObjectKey>,
        context: &mut ElementContext,
    ) {
        if let Some(child_ro_key) = child_ro {
            self.insert_child_render_object(child_ro_key, context);
        }
    }

    fn rebuild(&mut self, new_widget: Box<dyn Any>, context: &mut ElementContext) {
        // Same logic as update().
        self.update(new_widget, context);
    }

    fn focus_attachment(&self) -> &Option<FocusAttachment> {
        &self.focus_attachment
    }

    fn focus_attachment_mut(&mut self) -> &mut Option<FocusAttachment> {
        &mut self.focus_attachment
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::widgets::Text;

    struct TestEnv {
        value: u32,
        child: Box<dyn Widget>,
    }

    impl Clone for TestEnv {
        fn clone(&self) -> Self {
            Self {
                value: self.value,
                child: self.child.clone_boxed(),
            }
        }
    }

    impl TestEnv {
        fn new(value: u32, child: impl Widget + 'static) -> Self {
            Self {
                value,
                child: Box::new(child),
            }
        }
    }

    impl InheritedWidget for TestEnv {
        type Value = u32;
        fn value(&self) -> &u32 {
            &self.value
        }
        fn child(&self) -> &dyn Widget {
            self.child.as_ref()
        }
    }

    impl_widget_for_inherited!(TestEnv);

    #[test]
    fn blanket_widget_impl_creates_inherited_element() {
        let env = TestEnv::new(42, Text::new("hi"));
        let _elem = env.create_element(); // should not panic
    }

    #[test]
    fn blanket_widget_impl_child_delegates() {
        let env = TestEnv::new(42, Text::new("hi"));
        let child = Widget::child(&env).expect("inherited widget should have a child");
        assert!(child.as_any().downcast_ref::<Text>().is_some());
    }

    #[test]
    fn blanket_widget_impl_clone_boxed() {
        let env = TestEnv::new(42, Text::new("hi"));
        let cloned = env.clone_boxed();
        assert!(cloned.as_any().downcast_ref::<TestEnv>().is_some());
    }

    #[test]
    fn update_should_notify_default_compares_value() {
        let old = TestEnv::new(1, Text::new("a"));
        let new_same = TestEnv::new(1, Text::new("b")); // value same, child differs
        let new_diff = TestEnv::new(2, Text::new("c"));
        assert!(!old.update_should_notify(&old, &new_same));
        assert!(old.update_should_notify(&old, &new_diff));
    }
}
