[package]
name = "vexo"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
taffy = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
anyhow = { workspace = true }
glyphon = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
uniffi = { workspace = true }