[package]
name = "shared_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"] # staticlib for iOS, rlib for Desktop

[[bin]]
name = "uniffi-bindgen-swift"
path = "uniffi-bindgen-swift.rs"

[dependencies]
vexo = { path = "../vexo" } # Depend on the framework
uniffi = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
parking_lot = "0.12"
crossbeam = "0.8"


[build-dependencies]
uniffi = { version = "0.30.0", features = ["build"] }