//! Layout node types and constraints.
//!
//! Uses slotmap's `new_key_type!` macro to define generational key types
//! for layout nodes in the TaffyLayoutEngine.

use slotmap::new_key_type;

use crate::core::{Bounds, Point, Size};
use crate::core::Logical;

new_key_type! {
    /// Key for layout nodes in the `TaffyLayoutEngine`.
    ///
    /// Generated by `SlotMap::insert()`. Provides generational ABA protection:
    /// if a layout node is removed, the generation increments, and any stale
    /// `LayoutNodeKey` held elsewhere will no longer resolve to a valid node.
    pub struct LayoutNodeKey;
}

// ============================================================================
// LAYOUT CONSTRAINTS
// ============================================================================

/// Layout constraints that describe how a widget should be sized.
///
/// These constraints are provided by widgets during the layout phase
/// and used by the layout engine to compute final positions and sizes.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutConstraints {
    /// Minimum width in logical points.
    pub min_width: f32,
    /// Maximum width in logical points (f32::INFINITY for unbounded).
    pub max_width: f32,
    /// Minimum height in logical points.
    pub min_height: f32,
    /// Maximum height in logical points (f32::INFINITY for unbounded).
    pub max_height: f32,
    /// How much this widget should grow relative to siblings.
    pub flex_grow: f32,
    /// How much this widget should shrink relative to siblings.
    pub flex_shrink: f32,
}

impl Default for LayoutConstraints {
    fn default() -> Self {
        Self {
            min_width: 0.0,
            max_width: f32::INFINITY,
            min_height: 0.0,
            max_height: f32::INFINITY,
            flex_grow: 0.0,
            flex_shrink: 1.0,
        }
    }
}

impl LayoutConstraints {
    /// Create constraints for a fixed-size widget.
    pub fn fixed(width: f32, height: f32) -> Self {
        Self {
            min_width: width,
            max_width: width,
            min_height: height,
            max_height: height,
            flex_grow: 0.0,
            flex_shrink: 0.0,
        }
    }

    /// Create constraints for a fixed-size widget using a Size value.
    pub fn fixed_size(size: Size<Logical>) -> Self {
        Self::fixed(size.width, size.height)
    }

    /// Create constraints for a widget that fills available space.
    pub fn fill() -> Self {
        Self {
            min_width: 0.0,
            max_width: f32::INFINITY,
            min_height: 0.0,
            max_height: f32::INFINITY,
            flex_grow: 1.0,
            flex_shrink: 1.0,
        }
    }

    /// Create constraints with specific width, auto height.
    pub fn fixed_width(width: f32) -> Self {
        Self {
            min_width: width,
            max_width: width,
            ..Self::default()
        }
    }

    /// Create constraints with specific height, auto width.
    pub fn fixed_height(height: f32) -> Self {
        Self {
            min_height: height,
            max_height: height,
            ..Self::default()
        }
    }

    /// Check if the width is fixed (min == max).
    pub fn is_fixed_width(&self) -> bool {
        (self.min_width - self.max_width).abs() < f32::EPSILON
    }

    /// Check if the height is fixed (min == max).
    pub fn is_fixed_height(&self) -> bool {
        (self.min_height - self.max_height).abs() < f32::EPSILON
    }
}

// ============================================================================
// FLEX DIRECTION
// ============================================================================

/// Direction of flex layout.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum FlexDirection {
    /// Layout children in a row (horizontal).
    #[default]
    Row,
    /// Layout children in a column (vertical).
    Column,
    /// Layout children in a row, reversed.
    RowReverse,
    /// Layout children in a column, reversed.
    ColumnReverse,
}

// ============================================================================
// ALIGN ITEMS
// ============================================================================

/// How to align items in the cross axis.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum AlignItems {
    /// Stretch to fill.
    #[default]
    Stretch,
    /// Align to the start.
    Start,
    /// Align to the end.
    End,
    /// Center in the cross axis.
    Center,
}

// ============================================================================
// LAYOUT PADDING
// ============================================================================

/// Padding around a layout node.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LayoutPadding {
    pub left: f32,
    pub right: f32,
    pub top: f32,
    pub bottom: f32,
}

impl Default for LayoutPadding {
    fn default() -> Self {
        Self {
            left: 0.0,
            right: 0.0,
            top: 0.0,
            bottom: 0.0,
        }
    }
}

impl LayoutPadding {
    /// Create uniform padding on all sides.
    pub fn uniform(amount: f32) -> Self {
        Self {
            left: amount,
            right: amount,
            top: amount,
            bottom: amount,
        }
    }

    /// Create horizontal padding (left and right).
    pub fn horizontal(amount: f32) -> Self {
        Self {
            left: amount,
            right: amount,
            ..Self::default()
        }
    }

    /// Create vertical padding (top and bottom).
    pub fn vertical(amount: f32) -> Self {
        Self {
            top: amount,
            bottom: amount,
            ..Self::default()
        }
    }
}

// ============================================================================
// COMPUTED LAYOUT
// ============================================================================

/// The computed layout result for a node.
///
/// After the layout engine computes positions and sizes, each node
/// receives a ComputedLayout with its final bounds.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ComputedLayout {
    /// The key of the node this layout belongs to.
    pub id: LayoutNodeKey,
    /// The computed bounds (position and size) in logical coordinates.
    pub bounds: Bounds<Logical>,
}

impl ComputedLayout {
    /// Create a new computed layout.
    pub fn new(id: LayoutNodeKey, bounds: Bounds<Logical>) -> Self {
        Self { id, bounds }
    }

    /// Get the position (top-left corner).
    pub fn position(&self) -> Point<Logical> {
        Point::new(self.bounds.left, self.bounds.top)
    }

    /// Get the size.
    pub fn size(&self) -> Size<Logical> {
        Size::new(self.bounds.width(), self.bounds.height())
    }

    /// Get the x coordinate (left edge).
    pub fn x(&self) -> f32 {
        self.bounds.left
    }

    /// Get the y coordinate (top edge).
    pub fn y(&self) -> f32 {
        self.bounds.top
    }

    /// Get the width.
    pub fn width(&self) -> f32 {
        self.bounds.width()
    }

    /// Get the height.
    pub fn height(&self) -> f32 {
        self.bounds.height()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_layout_constraints_fixed() {
        let c = LayoutConstraints::fixed(100.0, 50.0);
        assert!(c.is_fixed_width());
        assert!(c.is_fixed_height());
        assert_eq!(c.min_width, 100.0);
        assert_eq!(c.max_width, 100.0);
    }

    #[test]
    fn test_layout_constraints_fill() {
        let c = LayoutConstraints::fill();
        assert!(!c.is_fixed_width());
        assert!(!c.is_fixed_height());
        assert_eq!(c.flex_grow, 1.0);
    }

    #[test]
    fn test_computed_layout() {
        let mut sm: slotmap::SlotMap<LayoutNodeKey, ()> = slotmap::SlotMap::with_key();
        let key = sm.insert(());

        let layout = ComputedLayout::new(
            key,
            Bounds::from_xywh(10.0, 20.0, 100.0, 50.0),
        );

        assert_eq!(layout.x(), 10.0);
        assert_eq!(layout.y(), 20.0);
        assert_eq!(layout.width(), 100.0);
        assert_eq!(layout.height(), 50.0);
    }

    #[test]
    fn test_layout_padding() {
        let p = LayoutPadding::uniform(10.0);
        assert_eq!(p.left, 10.0);
        assert_eq!(p.right, 10.0);
        assert_eq!(p.top, 10.0);
        assert_eq!(p.bottom, 10.0);

        let p = LayoutPadding::horizontal(5.0);
        assert_eq!(p.left, 5.0);
        assert_eq!(p.right, 5.0);
        assert_eq!(p.top, 0.0);
    }
}