//! Key types for the retain mode element tree.
//!
//! Uses slotmap's `new_key_type!` macro to define generational key types.
//! These keys provide ABA protection — when a slot is removed from the
//! SlotMap, the generation is bumped, invalidating any stale keys.

use slotmap::new_key_type;

new_key_type! {
    /// Key for elements in the `ElementRegistry`.
    ///
    /// Generated by `SlotMap::insert()`. Provides generational ABA protection:
    /// if an element is unmounted via `SlotMap::remove()`, the generation
    /// increments, and any stale `ElementKey` held elsewhere will no longer
    /// resolve to a valid element.
    pub struct ElementKey;
}

new_key_type! {
    /// Key for render objects in the `RenderObjectRegistry`.
    ///
    /// Generated by `SlotMap::insert()`. Provides generational ABA protection:
    /// if a render object is removed via `SlotMap::remove()`, the generation
    /// increments, and any stale `RenderObjectKey` held elsewhere will no
    /// longer resolve to a valid render object.
    pub struct RenderObjectKey;
}
